image: pnavaro/pandoc

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -q wheel
  - pip install -q -U jupyter-book==0.10.1

cache:
  paths:
    - .cache/pip
    - venv/

html_and_pdf:
  stage: build
  script: 
    - jupyter-book build .
    - jupyter-book build . --builder pdflatex
  tags:
    - docker
  artifacts:
    paths:
      - _build

linkcheck:
  stage: test
  before_script:
    - source venv/bin/activate
  script: jupyter-book build . --builder linkcheck
  allow_failure: true
  tags:
    - docker
  artifacts:
    paths:
      - _build

pages:
  stage: deploy
  before_script:
    - echo "no need of python here"
  script:
    - mv _build/html public
    - mv _build/latex/*.pdf public/
  tags:
    - docker
  artifacts:
    paths:
      - public
  only:
    - master
